import 'dart:convert';
import 'dart:io';

import 'package:file_picker/file_picker.dart';
import 'package:flutter/material.dart';
import 'package:intl/intl.dart';
import 'package:invoiso/l10n/app_localizations.dart';
import 'package:path_provider/path_provider.dart';
import 'package:invoiso/common/common.dart';
import 'package:invoiso/models/cash_ledger_entry.dart';
import 'package:invoiso/services/backend_services.dart';
import 'package:invoiso/services/pdf/pdf_font_service.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';

/// On-demand receipt for a Cash / UPI-Bank exchange (not generated by
/// default). Mirrors PaymentReceiptService's layout.
class ExchangeReceiptService {
  /// Opens the system print dialog for [entry] (an exchange).
  static Future<void> printReceipt(
    BuildContext context,
    CashLedgerEntry entry,
    String currencySymbol,
  ) async {
    try {
      final pdf = await _generatePDF(entry, currencySymbol);
      await Printing.layoutPdf(
        onLayout: (_) async => pdf.save(),
        name: '${entry.receiptNumber ?? entry.id}.pdf',
      );
    } catch (e) {
      if (context.mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(content: Text('Error generating receipt: $e')),
        );
      }
    }
  }

  /// Saves the receipt PDF through a save dialog as [fileName].
  static Future<void> download(
    BuildContext context,
    CashLedgerEntry entry,
    String currencySymbol,
  ) async {
    final l10n = AppLocalizations.of(context)!;
    final messenger = ScaffoldMessenger.of(context);
    try {
      final bytes = await (await _generatePDF(entry, currencySymbol)).save();
      final name = fileName(entry);
      String? savePath;
      try {
        savePath = await FilePicker.platform.saveFile(
          dialogTitle: l10n.reportsSavePdfReportTitle,
          fileName: name,
          type: FileType.custom,
          allowedExtensions: ['pdf'],
          bytes: Platform.isAndroid ? bytes : null,
        );
      } catch (_) {
        final dir = await getApplicationDocumentsDirectory();
        savePath = '${dir.path}/$name';
      }
      if (savePath == null) return; // cancelled
      if (!Platform.isAndroid) await File(savePath).writeAsBytes(bytes);
      messenger.showSnackBar(
          SnackBar(content: Text(l10n.reportsSavedAtMessage(savePath))));
    } catch (e) {
      messenger.showSnackBar(
          SnackBar(content: Text('Error generating receipt: $e')));
    }
  }

  /// `<customer>_receipt_<yyyyMMdd>_<HHmm>.pdf`; the customer part is left
  /// out when no name was entered. Anything but letters (incl. combining
  /// marks, e.g. Indic vowel signs) and digits becomes `_`.
  @visibleForTesting
  static String fileName(CashLedgerEntry e) {
    final customer = (e.customerName ?? '')
        .trim()
        .replaceAll(RegExp(r'[^\p{L}\p{M}\p{N}]+', unicode: true), '_')
        .replaceAll(RegExp(r'^_+|_+$'), '');
    final stamp = DateFormat('yyyyMMdd_HHmm').format(e.dateTime);
    return '${customer.isEmpty ? '' : '${customer}_'}receipt_$stamp.pdf';
  }

  static Future<pw.Document> _generatePDF(
      CashLedgerEntry e, String sym) async {
    final pdfTheme = await PdfFontService.loadTheme();
    final pdf = pw.Document(theme: pdfTheme);
    final company = await BackendServices.companyInfo.getCompanyInfo();
    final base64Logo = await BackendServices.settings.getCompanyLogo();
    final logoImage =
        base64Logo != null ? pw.MemoryImage(base64Decode(base64Logo)) : null;
    final dateFmt = (await BackendServices.settings.getDateFormat()).key;

    pdf.addPage(
      pw.Page(
        pageFormat: PdfPageFormat.a4,
        theme: pdfTheme,
        margin: const pw.EdgeInsets.all(40),
        build: (ctx) => _body(
          company: company,
          e: e,
          sym: sym,
          logoImage: logoImage,
          dateTime: DateFormat('$dateFmt, hh:mm a', 'en_US').format(e.dateTime),
        ),
      ),
    );
    return pdf;
  }

  static pw.Widget _body({
    required dynamic company,
    required CashLedgerEntry e,
    required String sym,
    required pw.MemoryImage? logoImage,
    required String dateTime,
  }) {
    const accentColor = PdfColors.indigo800;
    final upiToCash = e.entryType == CashLedgerEntry.upiToCash;
    final inAccount = upiToCash ? 'UPI/Bank' : 'Cash';
    final outAccount = upiToCash ? 'Cash' : 'UPI/Bank';
    final feeAccount =
        e.feeMethod == CashLedgerEntry.accountCash ? 'Cash' : 'UPI/Bank';
    const grey = pw.TextStyle(fontSize: 9, color: PdfColors.grey700);

    return pw.Column(
      crossAxisAlignment: pw.CrossAxisAlignment.start,
      children: [
        // ── Header: company info + logo ──────────────────────────────────
        pw.Row(
          mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
          crossAxisAlignment: pw.CrossAxisAlignment.start,
          children: [
            pw.Expanded(
              child: pw.Column(
                crossAxisAlignment: pw.CrossAxisAlignment.start,
                children: [
                  pw.Text(company?.name ?? '',
                      style: pw.TextStyle(
                          fontSize: 16,
                          fontWeight: pw.FontWeight.bold,
                          color: accentColor)),
                  if ((company?.address ?? '').isNotEmpty)
                    pw.Text(company!.address, style: grey),
                  if ((company?.phone ?? '').isNotEmpty)
                    pw.Text(company!.phone, style: grey),
                  if ((company?.email ?? '').isNotEmpty)
                    pw.Text(company!.email, style: grey),
                  if ((company?.gstin ?? '').isNotEmpty)
                    pw.Text('${taxLabel(company?.country)}: ${company!.gstin}',
                        style: grey),
                ],
              ),
            ),
            if (logoImage != null)
              pw.Container(
                width: 70,
                height: 70,
                child: pw.Image(logoImage, fit: pw.BoxFit.contain),
              ),
          ],
        ),
        pw.SizedBox(height: 16),
        pw.Divider(color: accentColor, thickness: 1.5),
        pw.SizedBox(height: 10),

        // ── Title ────────────────────────────────────────────────────────
        pw.Center(
          // Industry name for retail cash-service slips (AEPS / micro-ATM);
          // the service itself is named on the Type line.
          child: pw.Text('TRANSACTION RECEIPT',
              style: pw.TextStyle(
                  fontSize: 14,
                  fontWeight: pw.FontWeight.bold,
                  color: accentColor,
                  letterSpacing: 1)),
        ),
        pw.SizedBox(height: 14),

        // ── Meta ─────────────────────────────────────────────────────────
        pw.Container(
          padding: const pw.EdgeInsets.all(10),
          decoration: pw.BoxDecoration(
            color: PdfColors.grey100,
            borderRadius: pw.BorderRadius.circular(4),
          ),
          child: pw.Row(
            mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
            children: [
              pw.Column(
                crossAxisAlignment: pw.CrossAxisAlignment.start,
                children: [
                  _metaRow('Receipt #', e.receiptNumber ?? '-'),
                  pw.SizedBox(height: 4),
                  _metaRow('Type',
                      upiToCash ? 'UPI Cash Withdrawal' : 'Cash to UPI Transfer'),
                ],
              ),
              _metaRow('Date', dateTime),
            ],
          ),
        ),

        // ── Customer ─────────────────────────────────────────────────────
        if (e.customerName != null || e.customerPhone != null) ...[
          pw.SizedBox(height: 14),
          pw.Text('CUSTOMER',
              style: pw.TextStyle(
                  fontSize: 9,
                  fontWeight: pw.FontWeight.bold,
                  color: PdfColors.grey600,
                  letterSpacing: 1)),
          pw.SizedBox(height: 4),
          if (e.customerName != null)
            pw.Text(e.customerName!,
                style:
                    pw.TextStyle(fontSize: 11, fontWeight: pw.FontWeight.bold)),
          if (e.customerPhone != null) pw.Text(e.customerPhone!, style: grey),
        ],

        pw.SizedBox(height: 16),
        pw.Divider(color: PdfColors.grey300),
        pw.SizedBox(height: 10),

        // ── Amounts ──────────────────────────────────────────────────────
        pw.Text('SUMMARY',
            style: pw.TextStyle(
                fontSize: 9,
                fontWeight: pw.FontWeight.bold,
                color: PdfColors.grey600,
                letterSpacing: 1)),
        pw.SizedBox(height: 8),
        pw.Container(
          decoration: pw.BoxDecoration(
            border: pw.Border.all(color: PdfColors.grey300),
            borderRadius: pw.BorderRadius.circular(4),
          ),
          child: pw.Column(
            children: [
              _summaryRow('Amount received ($inAccount)',
                  '$sym ${_fmt(e.exchangeAmount)}'),
              _summaryRow('Service fee (paid by $feeAccount)',
                  '$sym ${_fmt(e.serviceFee)}'),
              _summaryRow('Total paid by customer',
                  '$sym ${_fmt(e.exchangeAmount + e.serviceFee)}',
                  bold: true, highlight: PdfColors.indigo50),
              pw.Container(
                padding:
                    const pw.EdgeInsets.symmetric(horizontal: 10, vertical: 8),
                decoration: const pw.BoxDecoration(
                  color: PdfColors.green700,
                  borderRadius:
                      pw.BorderRadius.vertical(bottom: pw.Radius.circular(4)),
                ),
                child: pw.Row(
                  mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
                  children: [
                    pw.Text('Given to customer ($outAccount)',
                        style: pw.TextStyle(
                            fontSize: 11,
                            fontWeight: pw.FontWeight.bold,
                            color: PdfColors.white)),
                    pw.Text('$sym ${_fmt(e.exchangeAmount)}',
                        style: pw.TextStyle(
                            fontSize: 11,
                            fontWeight: pw.FontWeight.bold,
                            color: PdfColors.white)),
                  ],
                ),
              ),
            ],
          ),
        ),

        // ── Notes ────────────────────────────────────────────────────────
        if ((e.notes ?? '').isNotEmpty) ...[
          pw.SizedBox(height: 10),
          pw.Text('Notes',
              style: pw.TextStyle(
                  fontSize: 9,
                  fontWeight: pw.FontWeight.bold,
                  color: PdfColors.grey600)),
          pw.SizedBox(height: 3),
          pw.Text(e.notes!,
              style: const pw.TextStyle(fontSize: 9, color: PdfColors.grey800)),
        ],

        pw.Spacer(),
        pw.Divider(color: PdfColors.grey300),
        pw.Center(
          child: pw.Text('Thank you!',
              style: pw.TextStyle(
                  fontSize: 9,
                  color: accentColor,
                  fontStyle: pw.FontStyle.italic)),
        ),
      ],
    );
  }

  static pw.Widget _metaRow(String label, String value) => pw.Row(
        mainAxisSize: pw.MainAxisSize.min,
        children: [
          pw.Text('$label: ',
              style: const pw.TextStyle(fontSize: 9, color: PdfColors.grey600)),
          pw.Text(value,
              style: pw.TextStyle(fontSize: 9, fontWeight: pw.FontWeight.bold)),
        ],
      );

  static pw.Widget _summaryRow(String label, String value,
      {bool bold = false, PdfColor? highlight}) {
    final style = pw.TextStyle(
        fontSize: 10,
        fontWeight: bold ? pw.FontWeight.bold : pw.FontWeight.normal);
    return pw.Container(
      padding: const pw.EdgeInsets.symmetric(horizontal: 10, vertical: 7),
      color: highlight,
      child: pw.Row(
        mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
        children: [pw.Text(label, style: style), pw.Text(value, style: style)],
      ),
    );
  }

  static String _fmt(double v) => NumberFormat('#,##0.00').format(v);
}
